# Master script: reproduces every table and figure of the paper.
# Run from the repository root, e.g.:  Rscript run_all.R
#
# Steps (each script is standalone and can also be run individually):
#   1. R/02_fit_priors_kl.R                 derive the three priors by KL
#                                           (values are cached in
#                                           R/01_priors_config.R; skip unless
#                                           the targets change)     ~5 min
#   2. R/03_calibrate_weights.R             prior-based a* lookup table
#                                           (paper Table a_star_lookup) ~45 min
#   3. R/04_simulation_estimation_figures.R estimation figures (Figs 3-8) ~10 min
#   4. R/05_simulation_prior_sensitivity.R  sensitivity heatmaps + counts ~35 min
#   5. R/06_application_tvsfp.R             TVSFP Tables 2-4 + McNemar   ~20 min
#   6. R/07_application_figures.R           TVSFP surfaces + error curves ~10 min
#
# Outputs go to Figures/ (PNG) and output/ (CSV, RDS, TeX fragments); both
# directories are git-ignored and fully regenerated by this script.
# Total runtime: roughly 2 hours.

steps <- c(
  "R/02_fit_priors_kl.R",
  "R/03_calibrate_weights.R",
  "R/04_simulation_estimation_figures.R",
  "R/05_simulation_prior_sensitivity.R",
  "R/06_application_tvsfp.R",
  "R/07_application_figures.R"
)

t0 <- Sys.time()
for (s in steps) {
  cat(sprintf("\n========== %s ==========\n", s))
  t1 <- Sys.time()
  source(s, echo = FALSE)
  cat(sprintf("[%s finished in %.1f min | %.1f min total]\n",
              s,
              as.numeric(difftime(Sys.time(), t1, units = "mins")),
              as.numeric(difftime(Sys.time(), t0, units = "mins"))))
}

cat(sprintf("\nAll steps completed in %.1f min.\n",
            as.numeric(difftime(Sys.time(), t0, units = "mins"))))
