# Write and read result tables. Each table is saved unrounded as CSV, with a
# plain TeX copy, in results/.

fbst_tex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\", "\\textbackslash{}", x, fixed = TRUE)
  for (s in c("&", "%", "$", "#", "_")) x <- gsub(s, paste0("\\", s), x, fixed = TRUE)
  x
}

fbst_write_table <- function(data, name) {
  stopifnot(is.data.frame(data))
  name <- sub("\\.(csv|tex)$", "", name)
  p <- file.path(fbst_output_dir(), name)
  dir.create(dirname(p), recursive = TRUE, showWarnings = FALSE)
  write.csv(data, paste0(p, ".csv"), row.names = FALSE, na = "NA")
  formatted <- lapply(data, function(x) {
    if (is.numeric(x)) ifelse(is.na(x), "NA", format(x, digits = 10, trim = TRUE, scientific = NA)) else as.character(x)
  })
  vals <- if (nrow(data)) do.call(cbind, lapply(formatted, fbst_tex_escape)) else matrix(character(), 0, ncol(data))
  rows <- if (nrow(data)) apply(vals, 1, function(x) paste0(paste(x, collapse = " & "), " \\\\")) else character()
  writeLines(c(
    paste0("% Generated by version ", FBST_VERSION),
    paste0("\\begin{tabular}{", paste(rep("l", ncol(data)), collapse = ""), "}"), "\\hline",
    paste0(paste(fbst_tex_escape(names(data)), collapse = " & "), " \\\\"), "\\hline",
    rows, "\\hline", "\\end{tabular}"
  ), paste0(p, ".tex"))
  invisible(paste0(p, ".csv"))
}

fbst_read_table <- function(name) {
  path <- file.path(fbst_output_dir(), paste0(name, ".csv"))
  if (!file.exists(path)) return(NULL)
  utils::read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
}
